name: "All Test"

on:
  push:
   paths:
    - '.github/workflows/ci.yml'
    - 'bin/**'
  repository_dispatch:
    types: ['run-all-test']

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
     fail-fast: false
     matrix:
      script: ["./nvim.sh", "./fish.sh", "./nodebrew.sh"]

    steps:
     - uses: actions/checkout@v2
     - name: unit-test of ${{matrix.script}}
       working-directory: ./bin/scripts
       run: bash -x ${{matrix.script}}

  ubuntu-vanilla:
   runs-on: ubuntu-latest
   if: ${{ success() }}
   needs: "unit-test"
   steps:
     - name: init-test of Ubuntu Vanilla
       run: |
         curl -o - "https://raw.githubusercontent.com/Kazanami/dotfiles/master/bin/install.sh" | bash

  containers:
    runs-on: ubuntu-latest
    needs: "unit-test"
    strategy:
      fail-fast: false
      matrix:
        cont_oses: ["ubuntu:latest", "centos:latest", "alpine:latest"]
    container: ${{ matrix.cont_oses }}
    steps:
      - name: init-test of Container (${{ matrix.cont_oses }})
        run: |
          wget -O - "https://raw.githubusercontent.com/Kazanami/dotfiles/master/bin/install.sh" | bash -x
