name: "Init my script test"

on:
  push:
   paths:
    - '.github/workflows/**.yml'
    - 'bin/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
     fail-fast: false
     matrix:
      script: ["./nvim.sh", "./fish.sh", "./nodebrew.sh"]

    steps:
     - uses: actions/checkout@v2
     - name: unit-test of ${{matrix.script}}
       working-directory: ./bin/scripts
       run: bash -x ${{matrix.script}}

  init-test:
    runs-on: ubuntu-latest
    needs: "unit-test"
    steps:
      - uses: actions/checkout@v2
      - name: initilize dotfiles test
        working-directory: ./bin
        run: |
          ./install.sh
          bash -c "ls -lsa ~"
          bash -c "sudo apt install tree -y"
          bash -c "tree -l ~"

  ubuntu-containar:
    runs-on: ubuntu-latest
    needs: "init-test"
    container: ubuntu:latest
    steps:
      - name: Test Ubuntu container
        run: |
          curl -o - https://raw.githubusercontent.com/Kazanami/dotfiles/master/bin/install.sh | bash
