name: "Init my script test"

on:
  push:
   path:
    - '.github/workflows/init-test.yml'
    - 'bin/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
     fail-fast: false
     matrix:
      script: ["./nvim.sh", "./fish.sh"]

    steps:
     - uses: actions/checkout@v2
     - name: unit-test of ${{matrix.script}}
       working-directory: ./bin/scripts
       run: bash -x ${{matrix.script}}
  init-test:
    runs-on: ubuntu-latest
    needs: "unit-test"
    steps:
      - uses: actions/checkout@v2
      - name: initilize dotfiles test
        working-directory: ./bin
        run: ./install.sh
        run: bash -c "ls -lsa"
