name: "Init my script test"

on:
  push:
   paths:
    - '.github/workflows/*.y?ml'
    - 'bin/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
     fail-fast: false
     matrix:
      script: ["./nvim.sh", "./fish.sh", "./nodebrew.sh"]

    steps:
     - uses: actions/checkout@v2
     - name: unit-test of ${{matrix.script}}
       working-directory: ./bin/scripts
       run: bash -x ${{matrix.script}}

  init-test:
    runs-on: ubuntu-latest
    needs: "unit-test"
    strategy:
      fail-fast: false
      matrix:
        oses: ["ubuntu:latest", "centos:latest"]
    container: ${{matrix.oses}}
    steps:
      - uses: actions/checkout@v2
      - name: initilize dotfiles test
        working-directory: ./bin
        run: |
          apt install sudo
          ./install.sh
          bash -c "ls -lsa ~"
          bash -c "sudo apt install tree -y"
          bash -c "tree -l ~"
