name: Ubuntu Vanilla

on:
  repository_dispatch:
    types: ['init_test_on_ubuntu_vanilla', 'single_test']
    
jobs:
  ubuntu-vanilla:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'
    steps:
      - name: "Run dotfiles Install"
        run: |
         curl -o - "https://raw.githubusercontent.com/Kazanami/dotfiles/master/bin/install.sh" | bash
