name: Ubuntu (Container)

on:
  push:
    branches: ['master']
    
  repository_dispatch:
    types: ['init-test', 'single_test_ubuntu_mini']

jobs:
  ubuntu-container:
    runs-on: ubuntu-latest
    container: "ubuntu:latest"
    if: github.event_name == 'repository_dispatch'
    steps:
      - name: "Run dotfiles Install"
        run: |
         apt update && apt install -y wget sudo software-properties-common
         wget -O - "https://raw.githubusercontent.com/Kazanami/dotfiles/master/bin/install.sh" | bash -x
