name: "Ubuntu (no-container)"

on:
  repository_dispatch:
    types: [run_init_test]

jobs:
  ubuntu-vanilla:
    runs-on: ubuntu-latest
    steps:
      - name: "Run dotfiles Install"
        run: |
         curl -o - "https://raw.githubusercontent.com/Kazanami/dotfiles/master/bin/install.sh" | bash
