name: "Init my script test"

on:
  push:
   paths:
    - '.github/workflows/unit-test.yml'
    - 'bin/**'


jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
     fail-fast: false
     matrix:
      script: ["./nvim.sh", "./fish.sh", "./nodebrew.sh"]

    steps:
     - uses: actions/checkout@v2
     - name: unit-test of ${{matrix.script}}
       working-directory: ./bin/scripts
       run: bash -x ${{matrix.script}}

  trigger-send:
   runs-on: ubuntu-latest
   needs: "unit-test"
   steps:
     - name: Send trigger init test
       uses: peter-evans/repository-dispatch@v1
       with:
         token: ${{ secrets.REPO_TOKEN }}
         repository: Kazanami/dotfiles
         event-type: init_test_on_ubuntu
         client-payload: '{"ref": "${{ github.ref }}" , "sha": "${{ github.sha }}"}'
       #run: |
       #   curl -X POST -H "Authorization: token ${{secrets.REPO_TOKEN}}" \
       #      -H "Content-Type: application/json" \
       #      https://api.github.com/repos/Kazanami/dotfiles/dispatches \
       #      --data '{"event_type":"run_init_test","client_payload":{"test":true}}'
