name: "Which Test"

on:
  push:
   branches: [ 'master' ]

jobs:
  containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cont_oses: ["ubuntu:latest", "centos:latest", "alpine:latest"]
    container: ${{ matrix.cont_oses }}
    steps:
      - name: curl or wget of Container (${{ matrix.cont_oses }})
        run: |
          echo `which curl`
          echo `which wget`
